import { motion } from 'framer-motion'
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { chartKeys } from './data/monthlyFinance'

const money = (value) => `R$ ${Number(value).toLocaleString('pt-BR')}`
const tooltip = { background: 'rgba(2,6,23,.94)', border: '1px solid rgba(255,255,255,.14)', borderRadius: 12, color: '#fff' }
export default function FinanceCharts({ data, activeKeys, toggleKey, selected }) {
  const donut = [{ name: 'Fixas', value: selected.fixed }, { name: 'Variáveis', value: selected.variable }]
  return <motion.div initial={{ opacity: 0, scale: .98 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} className="grid gap-4">
    <div className="h-[250px] rounded-2xl border border-white/10 bg-white/5 p-2 backdrop-blur-xl sm:h-[300px] sm:p-3 lg:h-[330px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ left: -18, right: 4, top: 4, bottom: 4 }}><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false} /><XAxis dataKey="month" stroke="#94a3b8" fontSize={10} tickFormatter={(value) => value.slice(0, 3)} /><YAxis stroke="#94a3b8" fontSize={10} tickFormatter={(value) => `${value / 1000}k`} /><Tooltip contentStyle={tooltip} formatter={money} /><Legend onClick={(entry) => toggleKey(entry.dataKey)} wrapperStyle={{ cursor: 'pointer', fontSize: 10 }} />{chartKeys.map(([key, label, color]) => activeKeys.includes(key) && <Bar key={key} dataKey={key} name={label} fill={color} radius={[4, 4, 0, 0]} animationDuration={450} />)}</BarChart></ResponsiveContainer></div>
    <div className="grid gap-4 sm:grid-cols-[180px_1fr]"><div className="h-[170px] rounded-2xl border border-white/10 bg-white/5 p-2"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={donut} dataKey="value" innerRadius={42} outerRadius={66} paddingAngle={4}>{donut.map((_, index) => <Cell key={index} fill={index === 0 ? '#94a3b8' : '#3b82f6'} />)}</Pie><Tooltip contentStyle={tooltip} formatter={money} /></PieChart></ResponsiveContainer></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><span className="text-xs text-slate-400">Margem de lucro</span><strong className="mt-2 block font-display text-3xl text-blue-200">{Math.round((selected.profit / selected.revenue) * 100)}%</strong><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><motion.div initial={{ width: 0 }} animate={{ width: `${(selected.profit / selected.revenue) * 100}%` }} className="h-full rounded-full bg-blue-500" /></div><p className="mt-3 text-xs leading-5 text-slate-400">Distribuição de despesas e eficiência operacional do mês.</p></div></div>
  </motion.div>
}
